# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ubi Snippets
email: sebastian.h.alcantara@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi there. I'm Sebastián Alcántara, a chemical engineer with a love for
  coding, game design, gaming and maybe some exercise.
  In this blog I will share little bits of info that I find to be interesting
  about any of this topics.
baseurl: "/ubi-snippets" # the subpath of your site, e.g. /blog
url: "http://sebastian-alcantara.github.io/ubi-snippets" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SebastAlcantara
github_username:  sebastian-alcantara

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-146888655-1
show_excerpts: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
